### ISSUE TITLE
Cover error

### ISSUE THREAD

**Issue by Knocks83** [CloudNebby/Lasty#1]
In Lasty.exe if you scrobble a song without a cover after a song that have a cover, instead of replacing the cover image with the "missing cover" one it keeps the cover image of the previous song.

Song without a cover as first song scrobbled:
![lasty_2018-06-05_21-15-34](https://user-images.githubusercontent.com/22529815/40997637-ae437dc4-6905-11e8-95bb-5ca740af5f14.png)

Song with a cover:
![lasty_2018-06-05_21-15-50](https://user-images.githubusercontent.com/22529815/40997657-bf1de5da-6905-11e8-98d0-d164544e502d.png)

Song without a cover after the one that have a cover:
![lasty_2018-06-05_21-16-05](https://user-images.githubusercontent.com/22529815/40997667-c9e19c00-6905-11e8-82ac-6be181ccaea6.png)

**Comment by ale183** [comment]
@Knocks83 the problem will be fixed in the next version.
