### ISSUE TITLE
The first relase doesn't work

### ISSUE THREAD

**Issue by Knocks83** [CloudNebby/Lasty#3]
The first relase ([Lasty.Material.exe](https://github.com/CloudNebby/Lasty/releases/download/Experimental/Lasty.Material.exe)) doesn't work: when you insert a username it does nothing.

I insert my username:
![lasty material_2018-06-05_22-11-54](https://user-images.githubusercontent.com/22529815/41000210-8edc3ef0-690d-11e8-8289-dbc8d3bcb7ff.png)

When i click "View Profile" it opens this popup:
![lasty material_2018-06-05_22-12-01](https://user-images.githubusercontent.com/22529815/41000298-dfc1e9c8-690d-11e8-8574-4fff5957f753.png)

Then if i press "Accept" it returns back to the home page:
![lasty material_2018-06-05_22-13-24](https://user-images.githubusercontent.com/22529815/41000303-e494c27c-690d-11e8-8656-712da2ed19e6.png)

The same situation occours if i check the "Remember me" checkbox.

**Comment by ale183** [comment]
@Knocks83 the problem will be fixed in the next version.
